import { WebsiteRecord } from "@/lib/types";

export const seedWebsites: WebsiteRecord[] = [
  {
    id: "site-1",
    websiteName: "Fintech Growth Daily",
    url: "https://fintechgrowthdaily.com",
    ownerName: "Alicia Brooks",
    email: "alicia@fintechgrowthdaily.com",
    phone: "+1 202 555 0136",
    generalPrice: 180,
    sensitivePrice: 420,
    da: 58,
    dr: 63,
    backlinks: 28400,
    trustFlow: 31,
    language: "English",
    region: "North America",
    niche: "Finance",
    monthlyTraffic: 76000,
    turnaroundDays: 5,
    placementType: "guest-post",
    linkAttribute: "dofollow",
    status: "available",
    verified: true,
    note:
      "Strong editorial process, performs well for SaaS and fintech campaigns. Sensitive niche placements require manual review before approval.",
    lastUpdated: "2026-03-18",
  },
  {
    id: "site-2",
    websiteName: "Wellness Horizon",
    url: "https://wellnesshorizon.org",
    ownerName: "Priya Shah",
    email: "partnerships@wellnesshorizon.org",
    phone: "+44 20 7946 0812",
    generalPrice: 145,
    sensitivePrice: 310,
    da: 51,
    dr: 55,
    backlinks: 19450,
    trustFlow: 27,
    language: "English",
    region: "United Kingdom",
    niche: "Health",
    monthlyTraffic: 52400,
    turnaroundDays: 7,
    placementType: "niche-edit",
    linkAttribute: "dofollow",
    status: "available",
    verified: true,
    note:
      "Accepts health, CBD, supplements, and wellness content when compliance copy is included. Ideal for long-form placements with expert bylines.",
    lastUpdated: "2026-03-15",
  },
  {
    id: "site-3",
    websiteName: "Crypto Gazette Pro",
    url: "https://cryptogazettepro.net",
    ownerName: "Marco Leone",
    email: "editor@cryptogazettepro.net",
    phone: "+39 06 9480 4412",
    generalPrice: 220,
    sensitivePrice: 540,
    da: 64,
    dr: 71,
    backlinks: 48200,
    trustFlow: 36,
    language: "English",
    region: "Europe",
    niche: "Crypto",
    monthlyTraffic: 99200,
    turnaroundDays: 4,
    placementType: "homepage",
    linkAttribute: "sponsored",
    status: "reserved",
    verified: true,
    note:
      "Premium authority inventory with exceptional DR. Suitable for crypto, casino, and forex campaigns with sponsored disclosure requirements.",
    lastUpdated: "2026-03-10",
  },
  {
    id: "site-4",
    websiteName: "Startup Stack World",
    url: "https://startupstackworld.com",
    ownerName: "Daniel Kim",
    email: "hello@startupstackworld.com",
    phone: "+82 2 555 0188",
    generalPrice: 130,
    sensitivePrice: 260,
    da: 46,
    dr: 49,
    backlinks: 12680,
    trustFlow: 22,
    language: "English",
    region: "Asia-Pacific",
    niche: "Technology",
    monthlyTraffic: 38750,
    turnaroundDays: 6,
    placementType: "guest-post",
    linkAttribute: "dofollow",
    status: "available",
    verified: false,
    note:
      "Fast-moving tech audience with founders and B2B buyers. Verification pending on updated organic traffic screenshots from the owner.",
    lastUpdated: "2026-03-14",
  },
  {
    id: "site-5",
    websiteName: "iGaming Ledger",
    url: "https://igamingledger.co",
    ownerName: "Sofia Alvarez",
    email: "media@igamingledger.co",
    phone: "+34 91 123 4456",
    generalPrice: 250,
    sensitivePrice: 610,
    da: 62,
    dr: 68,
    backlinks: 53790,
    trustFlow: 40,
    language: "Spanish",
    region: "Spain",
    niche: "Casino",
    monthlyTraffic: 113200,
    turnaroundDays: 3,
    placementType: "link-insert",
    linkAttribute: "dofollow",
    status: "available",
    verified: true,
    note:
      "Top-performing casino inventory with strong trust metrics and quick turnarounds. Best used for Spanish and LATAM gaming campaigns.",
    lastUpdated: "2026-03-12",
  },
  {
    id: "site-6",
    websiteName: "Global Trade Frontier",
    url: "https://globaltradefrontier.com",
    ownerName: "Nathan Cole",
    email: "sales@globaltradefrontier.com",
    phone: "+1 646 555 0120",
    generalPrice: 170,
    sensitivePrice: 360,
    da: 54,
    dr: 59,
    backlinks: 22610,
    trustFlow: 29,
    language: "English",
    region: "Global",
    niche: "Forex",
    monthlyTraffic: 61840,
    turnaroundDays: 5,
    placementType: "niche-edit",
    linkAttribute: "nofollow",
    status: "sold",
    verified: true,
    note:
      "Excellent audience overlap for B2B, forex, and international payments. Last premium slot sold; expected to restock after editorial refresh.",
    lastUpdated: "2026-03-09",
  },
];
